### ISSUE TITLE
Version 3.1 does not publish the config, only the stubs.

### ISSUE THREAD

**Issue by julianovmartins** [bennett-treptow/laravel-migration-generator#15]
On running the command below:

```
php artisan vendor:publish --provider="LaravelMigrationGenerator\LaravelMigrationGeneratorProvider"
```

This publishes only the stubs for version 3.1.

**Comment by bennett-treptow** [comment]
See UPGRADE.md to see how to upgrade from 2.3 to 3.0 -- config is no longer publishable in favor of using .env variables
