### ISSUE TITLE
[BUG] ErrorException Required parameter $output follows optional parameter $tableNames

### ISSUE THREAD

**Issue by patake** [bennett-treptow/laravel-migration-generator#22]
**Package Version**
"laravel/sail": "^1.0.1",
"php": "^8.0",
"laravel/framework": "^8.12",

**Database Version**
Mysql 5.7.19

**Describe the bug**
When trying to run the command, I receive a Exception described below.
 ErrorException 
 Required parameter $output follows optional parameter $tableNames

**To Reproduce**
command: sail php artisan generate:migrations --connection=mysql2

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/22771185/116245462-5d002180-a73f-11eb-974c-b798916e92d2.png)

**Additional context**
Maybe the style of function declaration is deprecated on PHP 8.

PHP 8.0.2 (cli) (built: Feb 14 2021 14:21:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies
    with Xdebug v3.0.2, Copyright (c) 2002-2021, by Derick Rethans

**Comment by bennett-treptow** [comment]
This has been fixed in version 3.1.4. Thanks for reporting!

**Comment by bennett-treptow** [comment]
Fixed in 3.1.5 actually

**Comment by patake** [comment]
@bennett-treptow I run composer upgarde and now it's on version 3.1.5, up and running. Thanks a lot.

Using /var/www/html/tests/database/migrations as the output path..

 143/143 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
