### ISSUE TITLE
[BUG] "The `pgsql` driver is not supported at this time."

### ISSUE THREAD

**Issue by renege** [bennett-treptow/laravel-migration-generator#26]
**Package Version**
3.1.5

**Database Version**
PostgreSQL

**Describe the bug**
```
▶ php artisan generate:migrations --connection=pgsql
Using connection pgsql
The `pgsql` driver is not supported at this time.
```

**To Reproduce**
Use postgresql

**Expected behavior**
A migration dump of the postgresql database

**Comment by bennett-treptow** [comment]
The message provided is an accurate statement: The PostgreSQL driver does not exist. Only MySQL databases are supported currently.
