### ISSUE TITLE
[BUG] Call to a member function `useCurrent()` on null

### ISSUE THREAD

**Issue by kemp** [bennett-treptow/laravel-migration-generator#27]
**Package Version**: 3.1.5

**Database Version**: mysql  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu)) 

**Describe the bug**

Generating some tables with timestamps creates this syntax:

```php
$table->timestamps()->useCurrent();
```

which is not valid syntax because the `timestamps` function does not return a ColumnDefinition

**To Reproduce**

```sql
create table test_table
(
    id              int auto_increment
        primary key,
    created_at      timestamp       default CURRENT_TIMESTAMP not null,
    updated_at      timestamp                                 null on update CURRENT_TIMESTAMP
)
```

**Expected behavior**

Expected generation to create:

```php
$table->timestamp('created_at')->nullable()->useCurrent();
$table->timestamp('updated_at')->nullable()->useCurrentOnUpdate();
```

P.S. Your package is a huge time saver! Thank you so much.

**Comment by bennett-treptow** [comment]
Thanks for reporting! Checkout version 3.1.6 for the fix

**Comment by kemp** [comment]
Dang! You're fast!

Thanks.

**Comment by bennett-treptow** [comment]
@kemp Actually, quick question about your test table: Is this just your re-creation, or where did you get that output? The null part of the declaration is in the wrong place compared to what the `SHOW CREATE TABLE` does.

**Comment by kemp** [comment]
I got that definition from PHPStorm's table definition of a table that already existed in the database. I guess PHPStorm uses a different mechanism than `SHOW CREATE TABLE`?

**Comment by bennett-treptow** [comment]
> I got that definition from PHPStorm's table definition of a table that already existed in the database. I guess PHPStorm uses a different mechanism than `SHOW CREATE TABLE`?

I see. That should be fine then, since the package will just use the database to do the schema lookup. Just wanted to make sure MySQL 8 wasn't suddenly giving a different `SHOW CREATE TABLE` than what my 5.7 gives. Thanks!

**Comment by kemp** [comment]
Checked with `SHOW CREATE TABLE` just for fun and it gives the same output you described. Must be a PHPStorm thing. :shrug:

**Comment by bennett-treptow** [comment]
> Checked with `SHOW CREATE TABLE` just for fun and it gives the same output you described. Must be a PHPStorm thing.

I've noticed their 'Quick Documentation' looks more like a SQLite definition than MySQL as well. Must be something with how they abstract that so it works for all the DBMS they support.
