### ISSUE TITLE
Auto-incrementing in `id` field that should not have auto-incrementing.

### ISSUE THREAD

**Issue by julianovmartins** [bennett-treptow/laravel-migration-generator#3]
First of all, I want to thank you for this package. It saved me a lot of work.

The primary key that I set up in my original migration.
```
$table->unsignedInteger('id')->nullable(false)->primary();
```

The field generated by this package. In addition, the definition as a `primary key` is missing.
```
$table->increments('id');
```

In this table, specifically, there cannot be auto-increment in the `id` field since the ids are pre-established.

### Suggestion
Instead of using:
``` 
$table->integer(xx)->unsigned()
```
Use 
```
$table->unsignedInteger(xx)
```
According to the field types of [laravel 8](https://laravel.com/docs/8.x/migrations#available-column-types).

**Comment by bennett-treptow** [comment]
I have fixed the issue with a non-auto-incrementing primary key still being assigned the Laravel magic method `increments`.
If you have a look into all of the `increments` fields (tinyIncrements, mediumIncrements, increments, bigIncrements) -- they do indeed add a primary key for you.

I have also added a config option for you to prefer to have the `unsigned` prefix for the method names. Check out https://github.com/bennett-treptow/laravel-migration-generator/releases/tag/2.2.0
