### ISSUE TITLE
Ordering migration by foreign key requirement

### ISSUE THREAD

**Issue by spartyboy** [bennett-treptow/laravel-migration-generator#38]
The package doesn't order migration based on foreign key relation, assuming i have a table consisting of admins, roles, admin_roles, the package first create migration for admin_roles before that of admins and roles thereby causing incorrect foreign key as admin is supposed to have been migrated before the admin_roles

**Comment by bennett-treptow** [comment]
@spartyboy This in progress, but if you're in need of something now -- check out here: https://github.com/bennett-treptow/laravel-migration-generator/pull/31

**Comment by bennett-treptow** [comment]
@spartyboy This is now part of version 4.0.0 release!
