### ISSUE TITLE
Laravel Sail - mkdir(): Operation not permitted

### ISSUE THREAD

**Issue by hope22** [bennett-treptow/laravel-migration-generator#4]
Trying to use the with Laravel Sail and getting the following error:
`mkdir(): Operation not permitted`

**Comment by hope22** [comment]
Resolved, deleted the `tests/database` folder and manually created `tests/database/migrations` 👍🏼

**Comment by bennett-treptow** [comment]
Hey @hope22, PR #11 should have fixed this permissions issue. Updating to 2.3.* should get you that update
