### ISSUE TITLE
SQLSTATE[42000]: on generate:migration

### ISSUE THREAD

**Issue by betterapp** [bennett-treptow/laravel-migration-generator#42]
1/27 [▓░░░░░░░░░░░░░░░░░░░░░░░░░░░]   3%
   Illuminate\Database\QueryException 

  SQLSTATE[42000]: Syntax error or access violation: 1055 'be_f.o.user_id' isn't in GROUP BY (SQL: SHOW CREATE VIEW `view_operation_sum_all`)

**Comment by bennett-treptow** [comment]
This is not a migration generator issue -- likely an issue with your view definition. https://dev.mysql.com/doc/refman/8.0/en/group-by-handling.html ONLY_FULL_GROUP_BY likely is enabled.
