### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by c-myers1** [bennett-treptow/laravel-migration-generator#44]
**Package Version**
3.2

**Database Version**
MariaDB 10.3 (XAMPP 3.2.4)

**Describe the bug**
Migration files are successfully generated. I then do the following
1) move them from the test/database/migrations folder to database/migrations folder
2) create a blank database and set the .env file to point to this
3) run php artisan migrate

It gives this error on the very first table it attempts to create (i.e. nothing is successfully created):

    `PHP Fatal error:  Cannot declare class CreateAllActivitiesHistoryTable, because the name is already in use in 
    C:\Users\user1\dev\laravel\migratetest\database\migrations\create_all_activities_istory_table.php on line 7
    
       Symfony\Component\ErrorHandler\Error\FatalError
    
      Cannot declare class CreateAllActivitiesHistoryTable, because the name is already in use

      at C:\Users\user1\dev\laravel\migratetest\database\migrations\create_all_activities_history_table.php:7
          3▕ use Illuminate\Support\Facades\Schema;
          4▕ use Illuminate\Database\Schema\Blueprint;
          5▕ use Illuminate\Database\Migrations\Migration;
          6▕
          7▕ class CreateAllActivitiesHistoryTable extends Migration
          8▕ {
          9▕     /**
         10▕      * Run the migrations.
         11▕      *
    
    
       Whoops\Exception\ErrorException`

**To Reproduce**
As described above

**Expected behavior**
I expect the database structure to be created into this new blank database

**Screenshot**
![image](https://user-images.githubusercontent.com/42839510/126065402-5e86b61a-c4ca-464c-a1ee-1d7a860e5404.png)

**Additional context**
I have tried to fix with all suggestions [here](https://stackoverflow.com/questions/54765710/error-migrations-cannot-declare-class-x-because-the-name-is-already-in-use) but they do not work (except the grep commands since this is Windows 10 environment).

However I have checked the migrations folder and there is only one file for each migration so it's unclear to me where this class is being redeclared and throwing the error.

PHP version is 7.4.3

**Comment by bennett-treptow** [comment]
Firstly, change your LMG_OUTPUT_PATH or config/laravel-migration-generator.php `path` to `database/migrations` and then you won't have to copy files over.

My only other thought is that you need to `composer dump-autoload` and/or clear out your `bootstrap/cache` folder.

What does your composer.json's `autoload` value look like?
