### ISSUE TITLE
Suggested Enhancement: Connection feature

### ISSUE THREAD

**Issue by brantmessenger** [bennett-treptow/laravel-migration-generator#45]
Love the existing functionality. I ran the 4.0 version and everything worked great! Had to alter all my migrations to accommodate my use case. In my use case, I'm converting an existing MySQL database to an SQLite database.

Changed `Schema::create()` to `Schema::connection('sqlite_foo')->create()`

If we had a flag to use the connection name or the connection's database name that would be super helpful. As an extra having a template variable name for the database and/or connection so it could be used when creating and naming the migration files would be nice too.

Again very thankful for what you brought to the community. Thank you!!!

**Comment by bennett-treptow** [comment]
Hi @brantmessenger,

You could publish the config stubs for both the table and views and change your output file format to include the connection!

Your `stubs/vendor/laravel-migration-generator/table.stub` could look something like this:

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Create[TableName:Studly]Table extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::connection('sqlite_foo')->create('[TableName]', function (Blueprint $table) {
[Schema]
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::connection('sqlite_foo')->dropIfExists('[TableName]');
    }
}
```
