### ISSUE TITLE
Generate migration from mysql database. ->comment("...") not generated.

### ISSUE THREAD

**Issue by utopszkij** [bennett-treptow/laravel-migration-generator#60]
MYSQL COMMENT "xxxx" definition not generate     ->comment("xxxx") migration code.

I repaired two fillets, so this problem was solved.

see //+Utopszkij ......... //- Utopszkij comments!

https://drive.google.com/file/d/1kH9jQ5xWrtQ8m9QlThTGvGKCOvCt4GGf/view?usp=sharing

https://drive.google.com/file/d/10a1FANxZ-oCftARlKi5GTJj095v-8odh/view?usp=sharing

Fogler Tibor (Utopszkij)  tibor.fogler@gmail.com 2022.02.05.

**Comment by bennett-treptow** [comment]
Related to #53 and PR #47

**Comment by bennett-treptow** [comment]
Try version 4.1.1 @utopszkij to export comments, just released with the PR
