### ISSUE TITLE
[BUG] Apostrophes in column comment value not escaped

### ISSUE THREAD

**Issue by mchlbowyer** [bennett-treptow/laravel-migration-generator#62]
**Package Version**
What version are you running? 2.2.*, 3.*
4.1.2

**Database Version**
What database driver are you using? And what version is that database?
MySQL

**Describe the bug**
When generating migrations, if the table has a comment that contains an apostrophe, the apostrophe isn't escaped in the migration.

**To Reproduce**
Please include any stack traces and applicable .env / config changes you've made
Create a table with a comment that contains an apostrophe, then generate a migration.

**Expected behavior**
The apostrophes in comments should be escaped.

**Screenshots**
![image](https://user-images.githubusercontent.com/50271531/152782570-0b5768b5-8f54-48aa-b4e7-f7a107a3715a.png)

**Additional context**

**Comment by mchlbowyer** [comment]
This also happens when the default value contains an apostrophe too:
![image](https://user-images.githubusercontent.com/50271531/152783927-c1f96121-0fc3-4124-8686-5d9b8e20d0fa.png)

**Comment by bennett-treptow** [comment]
@mchlbowyer What is the full comment that is causing these issues?

**Comment by bennett-treptow** [comment]
@mchlbowyer Give 4.1.3 a try!
