### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rashadm404** [bennett-treptow/laravel-migration-generator#66]
**Package Version**
What version are you running? 4.2.1

**Database Version**
Mysql 5.7.37

**Describe the bug**
I encountered an error while testing:

> ParseError: syntax error, unexpected '0' (T_LNUMBER), expecting ')'

Debugging revealed that it's because of the migration file.

We've `b'0'` as a default value for the one of fields. 
It seems "Laravel migration generator" doesn't check ' (single quote). `default('b'0'')->`

**To Reproduce**
- Add `b'0'` as a default value for a field
- php artisan generate:migrations
- Check the migration file.

**Expected behavior**
Can we replace single quotes with double?

**Comment by bennett-treptow** [comment]
@rashadm404 This is fixed as of version 4.2.2
