### ISSUE TITLE
File malformatted when comments are present

### ISSUE THREAD

**Issue by Squad-G** [bennett-treptow/laravel-migration-generator#69]
**Package Version**
What version are you running? 4.2.2

**Database Version**
Mysql 8.0.27

**Describe the bug**

There seem to be an error from time to time (it doesn't seem consistent) when generating migrations.

There's a syntax error.

`public function up()`
`{`
`  Schema::create('warehouses', function (Blueprint $table) {`
`    $table->smallIncrements('warehouse_id')->unsigned()->primary();`
**`    $table->string('warehouse_name', 120)->default(' COMMENT 'The');`**
`    $table->dateTime('warehouse_created_utc', 6)->nullable();`
`    $table->dateTime('warehouse_modified_utc', 6)->nullable();`
`    $table->dateTime('warehouse_deleted_utc', 6)->nullable();`
`  });`
`}`

![image](https://user-images.githubusercontent.com/1221038/182436929-5c78f3dc-33e8-49c1-beb6-17481f0442c1.png)

Thanks

**Comment by bennett-treptow** [comment]
@Squad-G Could you run this query for me and copy that here? The default value there might be causing the issue, but just want to make sure.

```
SHOW CREATE FULL TABLE `warehouses`;
```

My guess is it looks like:
```
`warehouse_name` VARCHAR(120) NOT NULL DEFAULT '' COMMENTS 'The name of the warehouse'`
```

**Comment by bennett-treptow** [comment]
@Squad-G This is fixed in version 4.2.3 👍 
I was able to reproduce the issue using my guess above.

**Comment by Squad-G** [comment]
Thank you very much, friend.

It's working as expected.

Continue the good work!

**Comment by Squad-G** [comment]
Good evening Bennett,

Thank you for coming back to me. It's very much appreciated.

Here's the result of the query you asked. Your guess is indeed correct.

CREATE TABLE `warehouses` (  `warehouse_id` smallint unsigned NOT NULL
AUTO_INCREMENT,  `warehouse_name` varchar(120) CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'The name of the
warehouse',  `warehouse_created_utc` datetime(6) DEFAULT NULL,
 `warehouse_modified_utc` datetime(6) DEFAULT NULL,
 `warehouse_deleted_utc` datetime(6) DEFAULT NULL,  PRIMARY KEY
(`warehouse_id`) ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci

Cordialement,
David-Luc Méthot-Bélanger.
----------------------------------------------------------------

*Cellulaire :* +1 (514) 654-1491
