### ISSUE TITLE
Option to define/add the named indexes

### ISSUE THREAD

**Issue by julianovmartins** [bennett-treptow/laravel-migration-generator#7]
### Suggestion

This is just a suggestion.

In one of my original migrations, I set up a unique named index.
```
$table->string('name_base', 50)->default('')->unique('UniqueBaseName');
```

MySQL (SHOW CREATE TABLE tablename;):
```
UNIQUE KEY `UniqueBaseName` (`name_base`)
```

In the migration created by this package, the existing name of the unique index was not defined.
```
$table->string('name_base', 50)->default('')->unique();
```

This may also be an option in the config, as some indexes can be automatically named by the database.

**Comment by bennett-treptow** [comment]
This is now part of PR #8 . Check out those new config options for the `use_defined_unique_key_index_names` for your case @julianovmartins which will by default be turned on now. #9 Updated the single column modifier like `unique` to use those index names as well.
