### ISSUE TITLE
Generate Migration that would insert newly created migration files into migrate table

### ISSUE THREAD

**Issue by tprinty** [bennett-treptow/laravel-migration-generator#74]
Would be neat if I could add an additional flag to to the command such that an Additional migration file would be created with dates and timestamps set so it would run first. The migration would insert into the migrations table, all the files generated by the run. This way you could squash the migration files but these would NOT run in production causing a bigger problem.

**Comment by bennett-treptow** [comment]
Could you give me an example? I am not entirely following.

You want this option to enable you to insert the migrations that are created as a baseline of sorts? Wouldn't the [default Laravel squash](https://laravel.com/docs/10.x/migrations#squashing-migrations) help you out with that?
