### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by salih0vic** [bennett-treptow/laravel-migration-generator#75]
**Package Version**
What version are you running? 4.3

**Database Version**
MariaDB 10.6.7

**Describe the bug**
Error is thrown when running `php artisan migrate` for the portion of generated migration ex. `$table->timestamp('created_at')->default('current_timestamp()');`

**To Reproduce**
`CREATE TABLE `test` ( `id` INT NOT NULL AUTO_INCREMENT , `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;`

**Expected behavior**
Above should be translated to:
`$table->timestamp('created_at')->useCurrent();`

**Screenshots**

**Additional context**

**Comment by bennett-treptow** [comment]
Using the `CREATE TABLE` statement provided on version 4.3.2, I get the following output (which is what you're looking for):

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTestTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('test', function (Blueprint $table) {
            $table->integer('id')->primary();
            $table->timestamp('created_at')->useCurrent();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('test');
    }
}
```

In this case, it seems like the reproduction steps are not enough context if you are manipulating the return results of the `SHOW CREATE TABLE test`.

Closing as not reproducible.
