### ISSUE TITLE
[BUG] cannot generate migrations for multiple tables

### ISSUE THREAD

**Issue by khanakia** [bennett-treptow/laravel-migration-generator#76]
**Package Version**
What version are you running? 4.3.1

**Database Version**
MariaDB 10.6.7

**Describe the bug**
I cannot generate the migration for multiple tables tried many commands it simply generates the empty folder

**To Reproduce**
```
php artisan generate:migrations --table="countries,states"
```
**Expected behavior**
It should generate migrations for countries and states table

**Screenshots**
![Screenshot 2023-07-02 at 3 25 01 PM](https://github.com/bennett-treptow/laravel-migration-generator/assets/2174170/c44298a6-6e74-48f0-8f2e-032edafff45e)

![Screenshot 2023-07-02 at 3 25 14 PM](https://github.com/bennett-treptow/laravel-migration-generator/assets/2174170/4215742d-86fa-44f5-83b9-81901bb116dd)

**Additional context**
When i run this command `php artisan generate:migrations` it generates the migration for all the tables successfully. I want to generate migration only for specific tables

**Comment by bennett-treptow** [comment]
@khanakia To specify specific tables, you need to follow the standard Laravel [input options array](https://laravel.com/docs/10.x/artisan#option-arrays) syntax: `php artisan generate:migrations --table=countries --table=states`
