### ISSUE TITLE
[BUG] Cannot migrate the Default Time Stamp value

### ISSUE THREAD

**Issue by hallabalint** [bennett-treptow/laravel-migration-generator#77]
The solution, if you use ''CURRENT_TIMESTAMP' as a default value, the generation need to create this schema:
` $table->timestamp('date')->default(DB::raw('CURRENT_TIMESTAMP'));` 
and need to add this: `use Illuminate\Support\Facades\DB;`

**Comment by bennett-treptow** [comment]
@hallabalint Is there a reason `->timestamp('data')->useCurrent()` does not accomplish what you're looking for?

Could you provide an example of the table create statement using `SHOW CREATE TABLE table_name;`?
