### ISSUE TITLE
Migration does not generator properly if field has empty default value and apostrophe in comment

### ISSUE THREAD

**Issue by jtomlinson** [bennett-treptow/laravel-migration-generator#78]
**Package Version**
4.3.1

**Database Version**
MySQL 8.0.27

**Describe the bug**
I have quite a few varchar fields that have a default value of '' and a comment that contains an apostrophe, when this occurs the migration that generates looks like the following:
```php
->default(')->comment("Code to identify the part's manufacturer.")
```

**To Reproduce**
I was able to add a test to ColumnTokenizerTest that recreates the issue
```php
public function test_it_tokenizes_varchar_with_default_empty_string_and_comment_with_apostrophe()
{
    $columnTokenizer = ColumnTokenizer::parse("`testing` varchar(255) DEFAULT '' COMMENT 'test with an apostrophe ('')'");
    $columnDefinition = $columnTokenizer->definition();
    $this->assertEquals('', $columnDefinition->getDefaultValue());
    $this->assertEquals('test with an apostrophe (\')', $columnDefinition->getComment());
}
``` 

I was able to "fix" the issue locally by adding the following code to the BaseTokenizer class. This obviously isn't a valid fix, but was good enough to get around the issue for myself.

```php
$value = str_replace("DEFAULT ''", '----------', $value);

//first get rid of any single quoted stuff with '' around it
if (preg_match_all('/\'\'(.+?)\'\'/', $value, $matches)) {
    ray($matches);
    foreach ($matches[0] as $key => $singleQuoted) {
        $toReplace = $singleQuoted;
        $value = str_replace($toReplace, self::SINGLE_QUOTE_REPLACER . $matches[1][$key] . self::SINGLE_QUOTE_REPLACER, $value);
        $pruneSingleQuotes = true;
    }
}

$value = str_replace('----------', "DEFAULT ''", $value);
```

**Expected behavior**
I would expect a migration to be generated like below:
```php
->default('')->comment("Code to identify the part's manufacturer.")
```

**Additional context**
I was going to create a pull request to fix the issue, but I'm not great with regex and wasn't sure of the best way to fix the issue correctly.

**Comment by bennett-treptow** [comment]
This is fixed as of version 4.3.3 @jtomlinson 👍
