### ISSUE TITLE
How to use the LMG_OUTPUT_PATH for actual testing

### ISSUE THREAD

**Issue by renzocastillo** [bennett-treptow/laravel-migration-generator#82]
This is a wonderful solution and perfect for my testing needs since it created all the migrations from my long default migrations list. I was wondering if its actually possible  to use those migrations located at the specific folder, just for testing while leaving the default migrations path for the application . 

As I understand we can enable `LMG_RUN_AFTER_MIGRATIONS` so that whenever you do `php artisan migrate` after that `php artisan generate:migrations` gets executed .

My issue is, how can i set `php artisan test` to point to another migrations path and use `testing\database\migrations` for speeding up the tests. 

Is this possible?

**Comment by renzocastillo** [comment]
Just if you are looking for the same I saw this interesting [post ](https://stackoverflow.com/questions/56871071/laravel-specify-a-migration-folder-when-i-run-the-database-migrations-via-phphun)

**Comment by bennett-treptow** [comment]
@renzocastillo 

In your base `TestCase`, you can specify the following method to override the path for the test migrations directory:

```
use LazilyRefreshDatabase {
    migrateUsing as baseMigrateUsing;
    migrateFreshUsing as baseMigrateFreshUsing;
}

// OR
use RefreshDatabase {
    migrateUsing as baseMigrateUsing;
    migrateFreshUsing as baseMigrateFreshUsing;
}

 protected function migrateUsing()
    {
        return array_merge($this->baseMigrateUsing(), [
            '--path' => base_path('testing/database/migrations')
        ]);
    }
protected function migrateFreshUsing()
    {
        return array_merge($this->baseMigrateFreshUsing(), [
            '--path' => base_path('testing/database/migrations'),
        ]);
    }
```
