### ISSUE TITLE
[BUG] Creates multiple foreign key migrations that should be in the original file

### ISSUE THREAD

**Issue by secondmanveran** [bennett-treptow/laravel-migration-generator#86]
**Package Version**
4.4.0

**Database Version**
MySQL 8.0.19

**Describe the bug**
When running the `generate` command the package creates duplicate foreign key entry files.

**To Reproduce**
No changes to the default config other than clearing the output directory.

**Expected behavior**
Package should implement the foreign key inside the original table creation migration file, or at the very least, if it must create a separate file, it should not make duplicates of it.

**Screenshots**
<img width="605" alt="Screenshot 2024-04-03 at 1 13 42 PM" src="https://github.com/bennett-treptow/laravel-migration-generator/assets/97000801/79fcaed6-5643-4b5a-83ae-cc3f9757e5cd">

Thanks

**Comment by bennett-treptow** [comment]
@secondmanveran Can you provide the table schema for the related table(s)? `SHOW FULL CREATE TABLE `aterial_datas;`

**Comment by secondmanveran** [comment]
```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class() extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
   */
  public function up()
  {
    Schema::create('material_datas', function (Blueprint $table) {
      $table->id();
      $table->string('name');
      $table->unsignedInteger('company_id');
      $table->unsignedInteger('part_id')->nullable();
      $table->unsignedInteger('record_id');
      $table->unsignedInteger('material_id');
      $table->unsignedInteger('condition_id');
      $table->longText('payload')->nullable();
      $table->unsignedTinyInteger('mask')->default(0);
      $table->boolean('alternate')->default(0);
      $table->unsignedBigInteger('parent_id')->nullable();
      $table->unsignedBigInteger('screening_engine_id')->nullable();
      $table->unsignedDecimal('min', 7, 4)->nullable();
      $table->unsignedDecimal('max', 7, 4)->nullable();
      $table->string('recycle')->default('NONE');
      $table->unsignedTinyInteger('nano')->default(0);
      $table->unsignedBigInteger('role_id')->nullable();
      $table->longText('notes')->nullable();
      $table->timestamp('created_at')->useCurrent();
      $table->timestamp('updated_at')->useCurrent();

      $table->foreign('company_id', 'material_datas_company_id_foreign')->references('id')->on('companies')->onDelete('cascade')->onUpdate('cascade');
      $table->foreign('condition_id', 'material_datas_condition_id_foreign')->references('id')->on('conditions')->onDelete('cascade')->onUpdate('cascade');
      $table->foreign('material_id', 'material_datas_material_id_foreign')->references('id')->on('materials')->onDelete('cascade')->onUpdate('cascade');
      $table->foreign('part_id', 'material_datas_part_id_foreign')->references('id')->on('parts')->onDelete('cascade')->onUpdate('cascade');
      $table->foreign('record_id', 'material_datas_record_id_foreign')->references('id')->on('records')->onDelete('cascade')->onUpdate('cascade');
      $table->foreign('role_id', 'material_datas_role_id_foreign')->references('id')->on('substance_roles')->onDelete('cascade')->onUpdate('cascade');
      $table->foreign('screening_engine_id', 'material_datas_screening_engine_id_foreign')->references('id')->on('screening_engines')->onDelete('cascade')->onUpdate('cascade');
    });
  }

  /**
   * Reverse the migrations.
   *
   * @return void
   */
  public function down()
  {
    Schema::dropIfExists('material_datas');
  }
};
```

I'm not sure if this is what you wanted? I tried running the command you posted in MySQL and it just told me it was invalid.

**Comment by bennett-treptow** [comment]
> ```
> <?php
> 
> use Illuminate\Database\Migrations\Migration;
> use Illuminate\Database\Schema\Blueprint;
> use Illuminate\Support\Facades\Schema;
> 
> return new class() extends Migration
> {
>   /**
>    * Run the migrations.
>    *
>    * @return void
>    */
>   public function up()
>   {
>     Schema::create('material_datas', function (Blueprint $table) {
>       $table->id();
>       $table->string('name');
>       $table->unsignedInteger('company_id');
>       $table->unsignedInteger('part_id')->nullable();
>       $table->unsignedInteger('record_id');
>       $table->unsignedInteger('material_id');
>       $table->unsignedInteger('condition_id');
>       $table->longText('payload')->nullable();
>       $table->unsignedTinyInteger('mask')->default(0);
>       $table->boolean('alternate')->default(0);
>       $table->unsignedBigInteger('parent_id')->nullable();
>       $table->unsignedBigInteger('screening_engine_id')->nullable();
>       $table->unsignedDecimal('min', 7, 4)->nullable();
>       $table->unsignedDecimal('max', 7, 4)->nullable();
>       $table->string('recycle')->default('NONE');
>       $table->unsignedTinyInteger('nano')->default(0);
>       $table->unsignedBigInteger('role_id')->nullable();
>       $table->longText('notes')->nullable();
>       $table->timestamp('created_at')->useCurrent();
>       $table->timestamp('updated_at')->useCurrent();
> 
>       $table->foreign('company_id', 'material_datas_company_id_foreign')->references('id')->on('companies')->onDelete('cascade')->onUpdate('cascade');
>       $table->foreign('condition_id', 'material_datas_condition_id_foreign')->references('id')->on('conditions')->onDelete('cascade')->onUpdate('cascade');
>       $table->foreign('material_id', 'material_datas_material_id_foreign')->references('id')->on('materials')->onDelete('cascade')->onUpdate('cascade');
>       $table->foreign('part_id', 'material_datas_part_id_foreign')->references('id')->on('parts')->onDelete('cascade')->onUpdate('cascade');
>       $table->foreign('record_id', 'material_datas_record_id_foreign')->references('id')->on('records')->onDelete('cascade')->onUpdate('cascade');
>       $table->foreign('role_id', 'material_datas_role_id_foreign')->references('id')->on('substance_roles')->onDelete('cascade')->onUpdate('cascade');
>       $table->foreign('screening_engine_id', 'material_datas_screening_engine_id_foreign')->references('id')->on('screening_engines')->onDelete('cascade')->onUpdate('cascade');
>     });
>   }
> 
>   /**
>    * Reverse the migrations.
>    *
>    * @return void
>    */
>   public function down()
>   {
>     Schema::dropIfExists('material_datas');
>   }
> };
> ```
> 
> I'm not sure if this is what you wanted? I tried running the command you posted in MySQL and it just told me it was invalid.

@secondmanveran Sorry, it should have been `SHOW CREATE TABLE material_datas`;

**Comment by secondmanveran** [comment]
> ### material_datas

```sql
"CREATE TABLE `material_datas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `company_id` int unsigned NOT NULL,
  `part_id` int unsigned DEFAULT NULL,
  `record_id` int unsigned NOT NULL,
  `material_id` int unsigned NOT NULL,
  `condition_id` int unsigned NOT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `mask` tinyint unsigned NOT NULL DEFAULT '0',
  `alternate` tinyint(1) NOT NULL DEFAULT '0',
  `parent_id` bigint unsigned DEFAULT NULL,
  `screening_engine_id` bigint unsigned DEFAULT NULL,
  `min` decimal(7,4) unsigned DEFAULT NULL,
  `max` decimal(7,4) unsigned DEFAULT NULL,
  `recycle` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'NONE',
  `nano` tinyint unsigned NOT NULL DEFAULT '0',
  `role_id` bigint unsigned DEFAULT NULL,
  `notes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `material_datas_company_id_index` (`company_id`),
  KEY `material_datas_part_id_index` (`part_id`),
  KEY `material_datas_record_id_index` (`record_id`),
  KEY `material_datas_material_id_index` (`material_id`),
  KEY `material_datas_condition_id_index` (`condition_id`),
  KEY `material_datas_parent_id_index` (`parent_id`),
  KEY `material_datas_role_id_index` (`role_id`),
  KEY `material_datas_screening_engine_id_index` (`screening_engine_id`),
  CONSTRAINT `material_datas_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `material_datas_condition_id_foreign` FOREIGN KEY (`condition_id`) REFERENCES `conditions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `material_datas_material_id_foreign` FOREIGN KEY (`material_id`) REFERENCES `materials` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `material_datas_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `material_datas` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `material_datas_part_id_foreign` FOREIGN KEY (`part_id`) REFERENCES `parts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `material_datas_record_id_foreign` FOREIGN KEY (`record_id`) REFERENCES `records` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `material_datas_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `substance_roles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `material_datas_screening_engine_id_foreign` FOREIGN KEY (`screening_engine_id`) REFERENCES `screening_engines` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2970 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
```
> ### concern_lists

```sql
"CREATE TABLE `concern_lists` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `list_id` int unsigned NOT NULL,
  `sublist_id` int unsigned DEFAULT NULL,
  `parent_id` bigint unsigned DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `concern_lists_parent_id_foreign` (`parent_id`),
  KEY `concern_lists_list_id_index` (`list_id`),
  KEY `concern_lists_sublist_id_index` (`sublist_id`),
  CONSTRAINT `concern_lists_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `concern_lists` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
```

**Comment by bennett-treptow** [comment]
Ah, I see! It's a self-referential foreign key. I will take a look to see why the foreign keys are being handled how they are.

**Comment by bennett-treptow** [comment]
@secondmanveran Can you check out the PR I just opened, and see if that fixes it? #87

**Comment by danyelgithub** [comment]
I got the same problem and this fix works for me

**Comment by secondmanveran** [comment]
@bennett-treptow 

Tested and commented the PR. Works great 👍🏻
